### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by 3f6a** [openreview/openreview-py#1920]
```
>>> import openreview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/wrk/.venv/lib/python3.12/site-packages/openreview/__init__.py", line 1, in <module>
    from .openreview import *
  File "~/wrk/.venv/lib/python3.12/site-packages/openreview/openreview.py", line 10, in <module>
    import requests
  File "~/wrk/.venv/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "~/wrk/.venv/lib/python3.12/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "~/wrk/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "~/wrk/.venv/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

I am using Python 3.12.0, openreview-py==1.33

**Comment by melisabok** [comment]
We are currently using python 3.10 with no issue. Could you please use this Python version until we fix this issue?
