### ISSUE TITLE
Handle Forbidden error when getting the group

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#739]
```
Traceback (most recent call last):
  File "/home/openreview/openreview-py/openreview/tools.py", line 52, in get_group
    group = client.get_group(id = id)
  File "/home/openreview/openreview-py/openreview/openreview.py", line 209, in get_group
    response = self.__handle_response(response)
  File "/home/openreview/openreview-py/openreview/openreview.py", line 103, in __handle_response
    raise OpenReviewException(response.json()['errors'])
openreview.openreview.OpenReviewException: [{'type': 'forbidden', 'path': 'id', 'value': 'NeurIPS.cc/2020', 'user': 'OpenReview.net/Support'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pythonShellFile7894289795.py", line 56, in <module>
    process(client, note, invitation)
  File "/tmp/pythonShellFile7894289795.py", line 11, in process
    conference = openreview.helpers.get_conference(client, note.forum, SUPPORT_GROUP)
  File "/home/openreview/openreview-py/openreview/conference/helpers.py", line 8, in get_conference
    return builder.get_result()
  File "/home/openreview/openreview-py/openreview/conference/builder.py", line 1529, in get_result
    groups = self.__build_groups(id)
  File "/home/openreview/openreview-py/openreview/conference/builder.py", line 1373, in __build_groups
    group = tools.get_group(self.client, id = p)
  File "/home/openreview/openreview-py/openreview/tools.py", line 56, in get_group
    if not error.startswith('Group Not Found'):
AttributeError: 'dict' object has no attribute 'startswith'
```

**Comment by melisabok** [comment]
this is fixed now.
